### ISSUE TITLE
Change browser API to use typescript

### ISSUE THREAD

**Issue by BenLambertNcl** [symphonyoss/ContainerJS#124]
The Browser API does not currently use typescript. This should be changed to be consistent with the other 2 APIs

**Comment by BenLambertNcl** [comment]
Lots of the API methods have been left out of the browser API as they did not work. However, if we are going to use typescript and the typescript interfaces, what should we do when a method is called that doesn't work. 

I can see 2 possibilities:
* Throw an error, forcing to user to catch the rejected promise. The flow of the program will be different depending on if it was in a container or in the browser.
* Silently do nothing and return the resolved promise. This would allow the app to continue as normal, but the method did nothing. This would allow apps to run on browser + container, but there would be no effect on the window (i.e. it would not be minimized). This could allow be paired with a `console.warn` so users know the method has limited or no effect in browser.

I'm not sure which is the best way to go with this. Any help would be appreciated : - )

**Comment by ColinEberhardt** [comment]
How about (3)

- Define a minimal super-interface interface that the browser implements? This way you don't need to throw errors, instead you get static checks.

**Comment by BenLambertNcl** [comment]
Yeah I like that. I think that would make up the `core` part of the window API, so ill leave it out of this PR so it can be added when the interface has been changed. Thanks :+1:
