### ISSUE TITLE
Add specific OpenFin and Electron tests

### ISSUE THREAD

**Issue by AndyMJones** [symphonyoss/ContainerJS#126]
It would be nice to be able to add a tag so that a test only runs for OpenFin or only runs for Electron.

**Comment by jleft** [comment]
There is already an environment variable set when running the tests - `MOCHA_CONTAINER` - which could be conditionally used to run tests. E.g.:

```js
if (process.env.MOCHA_CONTAINER === 'electron') {
  it('should test something only in Electron', function() {
    // test
  });
}
```

I'm not sure how this might affect the test report though.
