### ISSUE TITLE
Determine distribution mechanism

### ISSUE THREAD

**Issue by ColinEberhardt** [symphonyoss/ContainerJS#132]
We've got quite a few different pieces in this project, I think the following is the complete list:

- The OpenFin implementation of the ssf APIs, within `api-openfin`, which are bundled via rollup into a single JS file
- The Browser (partial) implementation of the ssf APIs, within `api-browser`, which are bundled via rollup into a single JS file
- An electron based command line tool, within `api-electron` which launches a ContainerJS application. This includes the electron ssf API implementation (which is split between renderer and main process)

We also have (or will have soon) TypeScript definitions for the APIs

I think that the three items listed above should be distributed via npm - but probably worth having further discussion.

**Comment by BenLambertNcl** [comment]
I agree that we should distribute via npm. What might be better is to have 4 packages that we could install:
* `api-brower` - the browser `containerjs-api.js` file
* `api-electron` - the Electron preload script and main file
* `api-browser` - the OpenFin `containerjs-api.js` file
* `cli` - a CLI that is used to run all of the projects (i.e. the `ssf-electron` file) but that is generalized to run any of the containers (via a `--container` flag or similar). 

I think that is a better separation of concerns. This would require a small change to the CLI script (to run `openfin -l -c ...` for OpenFin and `chrome index.html ...` for browser for example), but we would probably have wanted that to happen anyway, just to make the startup of containers consistent.

**Comment by ColinEberhardt** [comment]
> a CLI that is used to run all of the projects (i.e. the ssf-electron file) but that is generalized to run any of the containers (via a --container flag or similar).

I liked that idea!

> api-electron - the Electron preload script and main file

I'm just wondering what you see the value of distributing just those component parts separately is? The CLI just makes them executable via the following:

https://github.com/symphonyoss/ContainerJS/blob/master/packages/api-electron/bin/ssf-electron

**Comment by BenLambertNcl** [comment]
My thought was that we could version the CLI independently from the APIs. For example, if the options for `--enable-sandbox` is removed/changed, if the CLI was bundled with each API, then the API version numbers would all be bumped, whereas if it was separate, only the CLI version number needs bumping. This may be a non issue but was just my initial thoughts. :-)

**Comment by ColinEberhardt** [comment]
That sounds like a very good idea to me. It would also make it easier for people to integrate these APIs into any existing electron-based applications they might have.

**Comment by jleft** [comment]
Publishing to npm sounds great to me.

Here are some thoughts of what we might want to publish, and the fields which we'd use in `package.json` as the entry points.

For `api-browser` and `api-openfin`:

* `main` - for use in CommonJS environments; TypeScript compiled to ES5 JavaScript with CommonJS modules
* `module` (previously `jsnext:main`) - for use in ES2015 environments; TypeScript compiled to ES5 JavaScript with ES2015 modules
* `browser` - for use in browser environments (can be included as a single file and exposed on `ssf` global); TypeScript compiled to an ES5 JavaScript UMD bundle (single file) (using both `tsc` and Rollup)
* `types` (`typings` is synonymous with `types`) - TypeScript typing (`.d.ts`) for the module

I'm uncertain what's most appropriate for `api-electron` and what we want to expose. The simplest would probably just exposing the code run in the main process, then we can just use `main` for the main entry point (and `types`, if we use TypeScript?). If we want to expose the API that runs in the renderer process, then we could do the same as for `api-browser` and `api-openfin`. If we want to expose the APIs that runs in both the main and renderer process, then we might need two separate packages, or a single package which uses some combination of both approaches.

**Comment by BenLambertNcl** [comment]
I think this can be closed, as we now have all packages distributed on npm. Any issues with releases should be made as new issues. Please feel free to reopen if there is more to discuss.
