### ISSUE TITLE
Create a gitter chatroom

### ISSUE THREAD

**Issue by ColinEberhardt** [symphonyoss/ContainerJS#145]
We'd like to use gitter to open up discussions with other developers (most immediately the team from Tick42). I've started the process, but it sounds like I'll need someone with admin access on the org to do some configuration:

https://gitter.zendesk.com/hc/en-us/articles/202460552-Why-isn-t-my-GitHub-organisation-appearing-

@maoo are you able to set this up for us?

**Comment by maoo** [comment]
I've manually added gitter in the list of Github Authorized OAuth Apps, should be fine now

**Comment by ColinEberhardt** [comment]
Thanks @maoo
