### ISSUE TITLE
Re-add test matrix to the documentation on gh-pages

### ISSUE THREAD

**Issue by BenLambertNcl** [symphonyoss/ContainerJS#150]
The test matrix was removed when the documentation became auto generated. This should be added back in.

**Comment by ColinEberhardt** [comment]
It would be great if this information could be captured within the TypeScript documentation, keeping it all in one place.

**Comment by BenLambertNcl** [comment]
How do you mean captured in the Typescript docs? As in added into the auto generation of the documentation?
