### ISSUE TITLE
Do we use Jekyll Plugins?

### ISSUE THREAD

**Issue by ColinEberhardt** [symphonyoss/ContainerJS#156]
I'm having problems running the site locally. In order to preview the documentation, I'd like to run:

```
$ jekyll serve

/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require': cannot load such file -- bundler (LoadError)
	from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/plugin_manager.rb:34:in `require_from_bundler'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/exe/jekyll:9:in `<top (required)>'
```

However, this fails due to the Gemfile https://github.com/symphonyoss/ContainerJS/blob/master/docs/Gemfile. I haven't dug into the details of the error, but found that if I delete this Gemfile it works! Is it really needed?

**Comment by BenLambertNcl** [comment]
[This](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/) is the tutorial we used to serve the site locally. The command used is `bundle exec jekyll serve`. The only problem is that the links are wrong (i.e. `http://localhost:4000/ContainerJS/docs/App` is served at  `http://localhost:4000/docs/App`).

**Comment by jleft** [comment]
> The only problem is that the links are wrong (i.e. `http://localhost:4000/ContainerJS/docs/App` is served at  `http://localhost:4000/docs/App`).

@BenLambertNcl - could you use the [`baseurl` option](https://jekyllrb.com/docs/configuration/#serve-command-options)?

**Comment by ColinEberhardt** [comment]
Ah, I've not followed that documentation recently. I think that approach is useful if you require jekyll plugins. Without plugins, all you need to do is run the following to build:

~~~
$ jekyll
~~~

Also, it allows live-reload style preview:


~~~
$ jekyll serve
~~~

**Comment by BenLambertNcl** [comment]
@jleft Yeah :+1:
@ColinEberhardt Is GFM not added in as a plugin? Maybe @JohnEz can clarify?

**Comment by ColinEberhardt** [comment]
What's `GFM`? :-)

**Comment by BenLambertNcl** [comment]
GitHub Flavored  Markdown. I think it gets rendered slightly differently than normal markdown, but I could be wrong :-)

**Comment by ColinEberhardt** [comment]
Oh yes, the joy of using a syntax that lacks a standard: https://en.wikipedia.org/wiki/Markdown#Standardization

**Comment by AndyMJones** [comment]
Yeah I could be wrong but I am pretty sure there is a gh-pages plugin that helps with style at least. Not sure if it is also used for loading the metadata at the top of the file or if that's just normal jekyll code.

**Comment by ColinEberhardt** [comment]
The metadata at the top, (which is called front matter!) is a standard Jekyll thing.

I'd remove the Gemfile, and just see what happens - and at the same time, add a config.yml with teh baseurl as recommended by @jleft
