### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by ColinEberhardt** [symphonyoss/ContainerJS#177]
A couple of things ...

1. I think the gh-pages build should be triggered on every merge to master, even if the build fails. What do other think?
2. The most recent build failed (https://ci.appveyor.com/project/ColinEberhardt/containerjs/build/1.0.194), but the commit is showing a green tick https://github.com/symphonyoss/ContainerJS/commits/master

**Comment by BenLambertNcl** [comment]
1. Yeah that sounds like a good idea, although we won't have the test data, it's better than out of date API information
2. I'm working on it :-)

**Comment by ColinEberhardt** [comment]
For (1), I think my new build has a bug, it fails if it cannot find the test file. It should warn and continue.

**Comment by BenLambertNcl** [comment]
Also, the tests for OpenFin (and browser on my branch) keep failing on timeouts. I'm looking into it but increasing the timeouts doesn't seem to help.

**Comment by jleft** [comment]
I think (2) is still happening (if tests fail in `npm run test`), but the build is marked as successful on AppVeyor. e.g. https://ci.appveyor.com/project/ColinEberhardt/containerjs/build/1.0.236
