### ISSUE TITLE
ssf-electron Mac issues

### ISSUE THREAD

**Issue by ColinEberhardt** [symphonyoss/ContainerJS#196]
The globally installed `ssf-electron` fails on Mac

```
$ npm install --global containerjs-api-electron
...
$ ssf-electron 
env: node\r: No such file or directory
```

This looks like a [line endings issue](https://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-such-file-or-directo).

When installing globally I can see CRLF line endings:

```
$ file .../containerjs-api-electron/bin/ssf-electron 
.../containerjs-api-electron/bin/ssf-electron: a /usr/bin/env node script text executable, ASCII text, with CRLF line terminators
```

And changing this to LF fixes the issue.

Although, my git clone of the project is showing LF endings - I guess the auto line ending setting of git is automagically changing line endings when I checkout.

**Comment by BenLambertNcl** [comment]
From your link, it seems like we need to publish with LF line endings and it should work on all systems?

**Comment by ColinEberhardt** [comment]
Yes, I think that would fix it. This would likely require a bit of wrangling with git so that this file isn't subjected to auto-crlf.

**Comment by BenLambertNcl** [comment]
Could we not add a `.gitconfig` file to do that? Might it be easier to change the whole project to LF line endings?

**Comment by ColinEberhardt** [comment]
I think a `.gitattributes` file is more appropriate, it allows you to set line ending behaviour on a per-file basis. Fixing the line endings for files that are already committed is a bit more challenging.

**Comment by BenLambertNcl** [comment]
Ah, sounds good to me :-)
