### ISSUE TITLE
new ssf.Window has a different default location with OpenFin

### ISSUE THREAD

**Issue by ColinEberhardt** [symphonyoss/ContainerJS#211]
With electron a new window defaults to having the same location / bounds as the parent:
```
const window = new ssf.Window({ url: 'http://localhost:8080/popup.html', name: 'bob', autoShow: true });
```

With OpenFin it does not.

**Comment by ColinEberhardt** [comment]
It's also quite different in the browser also!

**Comment by BenLambertNcl** [comment]
If no x or y value is passed into the constructor, the window should display in the center of the screen. This seems to work for me in both Electron and OpenFin and browser, although browser is slightly off which I will fix. Wonder if this is a mac specific issue? The only difference is that OpenFin remembers the last position that window was in, which neither of the other 2 do.
