### ISSUE TITLE
Enable cla-bot

### ISSUE THREAD

**Issue by maoo** [symphonyoss/ContainerJS#217]
The Symphony Software Foundation requires contributors to sign a [Contributor License Agreement](https://symphonyoss.atlassian.net/wiki/display/FM/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement).

The [CLA bot (built by ScottLogic)](https://github.com/integration/cla-bot) can scan Github pull requests and make sure that all committer authors have a signed CLA with the Foundation (as it have been integrated with the Foundation CLA metadata repository).

Upon Pull Request submission, the bot will either:
- Add a label `cla-signed`, if all committer authors are included in the Foundation's contributors whitelist
- Add a comment with instructions on how to sign a CLA otherwise.

If the team agrees, I'd like to propose to enable the bot on this repository (which I can take care of)

**Comment by ColinEberhardt** [comment]
Agreed!

**Comment by maoo** [comment]
Just enabled! Please let me know if you find any issue (reopen this issue or create a new one) and I'd disable the integration right away, until we address the bot issue. Last thing I want is to interfere with the development activity.
