### ISSUE TITLE
TypeScript v2.4 caused validation errors on Generics

### ISSUE THREAD

**Issue by andy-lee-eng** [symphonyoss/ContainerJS#220]
[Announcing TypeScript 2.4](https://blogs.msdn.microsoft.com/typescript/2017/06/27/announcing-typescript-2-4/)

TypeScript 2.4 introduces "Stricter checking for generic functions", which I think is what's causing these errors.

e.g. the interface defines ScreenSnippet.capture() as returning a `Promise<string>`, but the actual function returns just a `Promise`

Example error:
```
src/screen-snippet.ts(1,7): error TS2420: Class 'ScreenSnippet' incorrectly implements interface 'ssf.ScreenSnippet'.
  Types of property 'capture' are incompatible.
    Type '() => Promise<{}>' is not assignable to type '() => Promise<string>'.
      Type 'Promise<{}>' is not assignable to type 'Promise<string>'.
        Type '{}' is not assignable to type 'string'.
```

**Comment by BenLambertNcl** [comment]
Thanks for that Andy! I did see the changes and wondered if that would break any of our code :-). Seems like we were actually resolving the promise with a string, but we didn't tell typescript, See #221.
