### ISSUE TITLE
Browser/Electron getting error "fin is not defined"

### ISSUE THREAD

**Issue by andy-lee-eng** [symphonyoss/ContainerJS#233]
```
containerjs-api-bundle:172 Uncaught ReferenceError: fin is not defined
    at Function.MessageService.subscribe (containerjs-api-bundle:172)
    at new Window (containerjs-api-bundle:313)
    at Function.Window.getCurrentWindow (containerjs-api-bundle:648)
    at containerjs-api-bundle:654
    at childTree (containerjs-api-bundle:4)
    at containerjs-api-bundle:5
```

The problem seems to be some code at the end of /packages/api-openfin/src/window.js that always executes (and expects window.fin to exist)

**Comment by BenLambertNcl** [comment]
Yeah you're right that is the cause of the problem. Inside the bundle, I thought that doing this:
```
if (!window.ssf) {
  if (window.fin) {
    api = require('containerjs-api-openfin');
  } else {
    api = require('containerjs-api-browser');
  }
} else {
  // api always overrides ssf because of the module name
  // so if there is already an implementation of ssf, we need to keep it
  api = window.ssf;
}
```

Would copy each api inside the if statements (i.e. `if (window.fin) { var Window = () ... }`). It actually builds to this:
```
if (!window.ssf) {
  if (window.fin) {
    api = require$$0;
  } else {
    api = require$$1;
  }
} else {
  // api always overrides ssf because of the module name
  // so if there is already an implementation of ssf, we need to keep it
  api = window.ssf;
}
```

Where require$$0 and require$$1 are the 2 APIs, meaning it executes both before the if statement is ran.

**Comment by ColinEberhardt** [comment]
That's odd - it would be good to know why it doesn't work now and what's changed. This did work before. For example, here's a very simple demo app, that I've just tested in the browser:

```
<!doctype html>
<title>ContainerJS Demo</title>
<h1>ContainerJS Demo</h1>
<div>ContainerJS status: <span id="status">initialising</span></div>
<button id="popup">pop up</button>

<script src="https://unpkg.com/containerjs-api-bundle@0.0.2/build/containerjs-bundle.js"></script>

<script>
  ssf.app.ready()
    .then(() => {
      const status = document.getElementById('status');
      status.innerText = 'ready';

      document.getElementById('popup')
        .addEventListener('click', () => {
          const popup = new ssf.Window({
            url: 'http://localhost:8080/popup.html',
            name: 'popup',
            autoShow: true
          });
        })
    });
</script>
```

I don't see any errors regarding `fin` not being declared when running in the browser.

**Comment by BenLambertNcl** [comment]
> `<script src="https://unpkg.com/containerjs-api-bundle@0.0.2/build/containerjs-bundle.js"></script>`

I could only get this to appear using the local copies. It's because of [this](https://github.com/symphonyoss/ContainerJS/blob/master/packages/api-openfin/src/window.ts#L528) that it gets executed, because both APIs are actually parsed and executed, but only 1 is actually used, we get the error.

**Comment by andy-lee-eng** [comment]
The code that introduced the problem was only added 4 days ago [commit](https://github.com/symphonyoss/ContainerJS/commit/0e8084719164ecd8ebd124e312a9eaa2ad624585), so I guess it isn't in the 0.0.2 version on unpkg.com?
