### ISSUE TITLE
Browser test results show in docs when no tests have been run

### ISSUE THREAD

**Issue by JDawes-ScottLogic** [symphonyoss/ContainerJS#272]
For example, `Window` tests are not run for the browser, but test results show the browser as failing:

![image](https://user-images.githubusercontent.com/11292375/28360931-e670f846-6c6e-11e7-8ae0-7ea229ca52cc.png)

**Comment by BenLambertNcl** [comment]
@JDawes-ScottLogic Can this be closed, or is there more work to be done with this?

**Comment by JDawes-ScottLogic** [comment]
It can be closed. There was talk about using N/A for not run, etc. but I'll log an issue with the full details for a proper discussion.
