### ISSUE TITLE
Move ScreenSnippet functionality to WindowCore

### ISSUE THREAD

**Issue by JDawes-ScottLogic** [symphonyoss/ContainerJS#275]
From the GoogleDoc:
>ScreenSnippet: Perhaps this should just be a method on a window?

This currently takes a snippet of the _window_ not the screen. Given that this is all it is doing as well, this makes more sense to be a method on a window. It also has the side effect of lowering it's visibility, i.e. it will no longer be a top level concept.

**Comment by BenLambertNcl** [comment]
I agree it makes much more sense to have it on the window. :+1:

**Comment by JDawes-ScottLogic** [comment]
As everything implements `ScreenSnippet`, this will be on `WindowCore`, not `Window`.
Updated the title to reflect this.

**Comment by JDawes-ScottLogic** [comment]
Having moved the implementation from `ScreenSnippet` to `WindowCore`, the question now arises of what we're taking a snippet of? Previously this was a class method on `ScreenSnippet`, so I've simply moved it over. However, this appears to have changed the semantics a little. Previously, to take a snippet, we would do this:
```javascript
var mySnippet = new ssf.ScreenSnippet();
mySnippet.capture()
.then(...);
```

This would take a snippet of the current window. Moving it to `WindowCore`, however, looks like this:
```javascript
var win = new ssf.Window(...);
win.capture()
.then(...);
```

This results in a new window opening, but `capture()` takes a snippet of the current window, not the window referenced by the `win` variable. Do we want to change the logic to take a snippet of the window `win` refers to, instead of the current window?

**Comment by JDawes-ScottLogic** [comment]
Logic changed to capture the child window. Only caveat is that for the browser, the same-domain restrictions apply.
