### ISSUE TITLE
Include shim layer in cli tools

### ISSUE THREAD

**Issue by ColinEberhardt** [symphonyoss/ContainerJS#302]
The Symphony code that relies on this API is now public. I'd like to start testing containerjs against this code.

Currently our Symphony compatibility or shim has to be included client-side. In order to test the currently deployed code it would have to be included as part of the preload script.

It would be ideal if this could be included via a command line arg on the two cli tools!

**Comment by andy-lee-eng** [comment]
Closed by https://github.com/symphonyoss/ContainerJS/pull/310
