### ISSUE TITLE
The docs should have links between types

### ISSUE THREAD

**Issue by ColinEberhardt** [symphonyoss/ContainerJS#321]
Foe example, when looking at documentation for `new Window(...)`, it would be useful to have a link to the `WindowOptions` type somewhere:

![image](https://user-images.githubusercontent.com/1098110/28869925-5632e858-7776-11e7-873a-af8e8436a87b.png)

**Comment by ColinEberhardt** [comment]
actually ... WindowOptions doesn't appear in the docs anywhere

**Comment by JDawes-ScottLogic** [comment]
WindowOptions documentation being missing is logged as #312

**Comment by JDawes-ScottLogic** [comment]
I've had a look, and this seems do-able, however we only have the type available at the point we're transforming `type-info.json`, and for interfaces we append `-interface` to the section id.

**Comment by JDawes-ScottLogic** [comment]
Possible solution is to strip the section id down to just the name of the type and add a css class if we need to identify the interfaces explicitly. This would let us assume the id to link to.

Only problem with this is we'd need a black or whitelist of types to prevent us attempting to link to non-ContainerJS types.
