### ISSUE TITLE
Publishing issues

### ISSUE THREAD

**Issue by ColinEberhardt** [symphonyoss/ContainerJS#328]
something seems to have gone wrong with the publish I just ran ...
if you look at the versions for one of our packages, e.g. `npm view containerjs-api-browser` ... it shows the latest (in this case 0.0.4)
... however, if you install, or request the current version, 0.0.3 is installed
looks like the `dist-tags.latestfield` for 0.0.4 points to 0.0.3 for some reason!

A few other general thoughts around release
 - should probably include `npm login` at the start of the instructions rather than the end
 - our current process involves using squash / merge for all PRs. This means that the tags are 'orphaned', i.e. they do not appear on the master branch. I *think* this is causing some issues with how lerna works
 - we should briefly document how lerna works. The version information is stored both in package.json and in tags - how does it use these?

**Comment by JDawes-ScottLogic** [comment]
Fixed the `latest` dist-tag for the packages on npm, so these should now install the latest version.

Need to update the documentation for publishing.
