### ISSUE TITLE
Mark packages private to prevent publishing them to npm

### ISSUE THREAD

**Issue by JDawes-ScottLogic** [symphonyoss/ContainerJS#329]
`containerjs-api-symphony-demo` and `containerjs-api-utility` should both be marked as private in their `package.json` in order to prevent them from being published to npm.

**Comment by ColinEberhardt** [comment]
good spot - should probably un-publish too

**Comment by JDawes-ScottLogic** [comment]
Resolved by #330

**Comment by ColinEberhardt** [comment]
NOTE: unpublish!

**Comment by JDawes-ScottLogic** [comment]
`containerjs-api-utility` is actually a required dependency (#339 ), and `containerjs-api-symphony-demo` hasn't been published, so no further work is required on this.
