### ISSUE TITLE
Review tests in docs

### ISSUE THREAD

**Issue by JDawes-ScottLogic** [symphonyoss/ContainerJS#332]
The docs currently imply we have failing tests, when the failures appear to be related to environment issues on appeveyor (https://ci.appveyor.com/project/ColinEberhardt/containerjs/build/1.0.530, https://ci.appveyor.com/project/ColinEberhardt/containerjs/build/1.0.534, https://ci.appveyor.com/project/ColinEberhardt/containerjs/build/1.0.539,
https://ci.appveyor.com/project/ColinEberhardt/containerjs/build/1.0.542).

A lot of the failures look like they are environment issues, rather than genuine failures (close test failures are fairly easy to reproduce by using a machine that is running the tests and interacting with other windows), but we continue and publish the docs with these failing tests.

Also, we currently publish the docs on every commit to `master`, not every release. Do we want to consider only updating the docs when we do a release?

**Comment by andy-lee-eng** [comment]
I think these problems are fixed by [this commit](https://github.com/symphonyoss/ContainerJS/commit/41b32f5c99c5fb2371df97d8f4cfee4ada7ffcd6)

Builds seem to be succeeding regularly now
