### ISSUE TITLE
Investigate using sematic-release

### ISSUE THREAD

**Issue by JDawes-ScottLogic** [symphonyoss/ContainerJS#334]
Investigate using [semantic-release](https://github.com/semantic-release/semantic-release) for the release process.

**Comment by JDawes-ScottLogic** [comment]
semantic-release probably won't work as we're using `lerna`, but it looks like there's a compatible fork: https://github.com/atlassian/lerna-semantic-release

**Comment by ColinEberhardt** [comment]
If it makes it simpler, I don't think it's a big issue if all of our lerna packages are versioning with the same number. My gut feeling is that this would be simpler from a semver perspective.

Anyhow, feels like a low priority over features / examples / testing at the moment, as long as releases have an easy to follow documented process

**Comment by JDawes-ScottLogic** [comment]
Duplicate of #232
