### ISSUE TITLE
Matrix of test coverage

### ISSUE THREAD

**Issue by ColinEberhardt** [symphonyoss/ContainerJS#91]
It would be great to have a matrix which indicates the overall test coverage of the APIs. Similar to this sort of thing:

https://kangax.github.io/compat-table/es6/

With this, plus our compatability tables, and API documentation, it does feel like it should be possible to code-gen the various outputs.

**Comment by ColinEberhardt** [comment]
For each API method we want the following:

- Documentation, what it does, params, etc ...
- Compatibility information
- Test coverage
- Perhaps a type definition #90 

Rather than having this information spread around in the code, it would be great if it was generated from source.

**Comment by ColinEberhardt** [comment]
I wonder if we could add meta-data to the tests?

```
// @tests ssf.Window.maximize
it('should maximize', () => {});
```

**Comment by BenLambertNcl** [comment]
I agree metadata would be nice. In the same vein, I think adding JSDoc to the API would be useful. Might be worth adding that as a new issue.
